'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, 
the first 10 terms will be:

1,2,3,5,8,13,21,34,55,89

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.

'''
Sum = 2
val = [1,2]
i = 0

while True:
    val[i] = val[0] + val[1]
    
    if val[i] > 4*10**6:
        break

    if (val[i] % 2) == 0:
        Sum += val[i]
    
    if i == 0:
        i +=1
    else:
        i -= 1
    
    
print(Sum)

    



